ALTER TABLE "Institution" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Institution" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;

UPDATE "Institution" SET "latitude" = 32.0463, "longitude" = 34.8428 WHERE "slug" = 'sheba' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.0805, "longitude" = 34.7892 WHERE "slug" = 'ichilov' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.0350, "longitude" = 34.7620 WHERE "slug" = 'wolfson' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.4510, "longitude" = 34.9120 WHERE "slug" = 'hillel-yaffe' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.8330, "longitude" = 34.9850 WHERE "slug" = 'rambam' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.8050, "longitude" = 34.9900 WHERE "slug" = 'bnai-zion' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 33.0090, "longitude" = 35.0940 WHERE "slug" = 'galilee' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.9660, "longitude" = 35.4960 WHERE "slug" = 'ziv' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.7480, "longitude" = 35.5390 WHERE "slug" = 'poria' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 31.6680, "longitude" = 34.5740 WHERE "slug" = 'barzilai' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 31.9660, "longitude" = 34.8410 WHERE "slug" = 'shamir' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 31.2580, "longitude" = 34.8010 WHERE "slug" = 'soroka' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.0910, "longitude" = 34.8680 WHERE "slug" = 'rabin-beilinson' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.0870, "longitude" = 34.8810 WHERE "slug" = 'rabin-hasharon' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.0920, "longitude" = 34.8680 WHERE "slug" = 'schneider' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.7850, "longitude" = 34.9660 WHERE "slug" = 'carmel' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.6220, "longitude" = 35.3190 WHERE "slug" = 'emek' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.1810, "longitude" = 34.9040 WHERE "slug" = 'meir' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 31.8760, "longitude" = 34.8090 WHERE "slug" = 'kaplan' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 29.5570, "longitude" = 34.9490 WHERE "slug" = 'yoseftal' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 31.7650, "longitude" = 35.1490 WHERE "slug" = 'hadassah-ein-kerem' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 31.7970, "longitude" = 35.2420 WHERE "slug" = 'hadassah-mount-scopus' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 31.7730, "longitude" = 35.2050 WHERE "slug" = 'shaare-zedek' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.3320, "longitude" = 34.8560 WHERE "slug" = 'laniado' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 31.8150, "longitude" = 34.6660 WHERE "slug" = 'assuta-ashdod' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.0890, "longitude" = 34.8340 WHERE "slug" = 'maayanei-hayeshua' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.7020, "longitude" = 35.2980 WHERE "slug" = 'nazareth-english' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.7040, "longitude" = 35.3030 WHERE "slug" = 'holy-family' AND ("latitude" IS NULL OR "longitude" IS NULL);
UPDATE "Institution" SET "latitude" = 32.7040, "longitude" = 35.3060 WHERE "slug" = 'saint-vincent' AND ("latitude" IS NULL OR "longitude" IS NULL);
