import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
const root='http://localhost:3105',out='/private/tmp/hitmachut-phase3c/screenshots';mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
let external=0;
async function context(mobile=false){const c=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000}});await c.route('**/*',r=>{if(new URL(r.request().url()).hostname==='localhost')return r.continue();external++;return r.abort();});return c;}
async function login(c,role){const p=await c.newPage();await p.goto(root+'/login?next=/placements');await p.locator('input[type=email]').fill(`phase3c-${role}@example.test`);await p.locator('input[type=password]').fill('Synthetic-Phase3C-Only!');await p.locator('button[type=submit]').click();await p.waitForURL(u=>u.pathname==='/placements');return p;}
try{
const anon=await context(true),page=await anon.newPage();await page.goto(root+'/placements');for(const name of ['סטודנט/ית לרפואה בישראל','סטודנט/ית ישראלי/ת לרפואה בחו״ל','סטאז׳ר/ית'])await page.getByRole('heading',{name,exact:true}).waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:out+'/local-overview-mobile.png',fullPage:true});await page.goto(root+'/admin/placements');assert(new URL(page.url()).pathname==='/login');console.log('PASS mobile three-route overview; anonymous operator denial');
const applicant=await context(true),a=await login(applicant,'student');await a.goto(root+'/admin/placements');assert(!await a.getByRole('heading',{name:'בקרת פיילוט סבבים ואלקטיבים'}).count());console.log('PASS authenticated applicant cannot access admin operations');
const admin=await context(),p=await login(admin,'admin');await p.goto(root+'/admin/placements');await p.getByRole('heading',{name:'בקרת פיילוט סבבים ואלקטיבים'}).waitFor();assert(await p.getByRole('button',{name:'מינוי חסום עד אישור מוסדי והשלמת האינטגרציה'}).isDisabled());await p.screenshot({path:out+'/local-admin-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:out+'/local-admin-mobile.png',fullPage:true});console.log('PASS real authenticated admin pending roles/readiness desktop/mobile');
const paths=['/api/placements/operations','/api/placements/documents','/api/clinical-rotations/applications','/api/clinical-rotations/groups','/api/clinical-rotations/identity','/api/admin/clinical-rotations/eligibility-imports','/api/clinical-rotations/hospital/offerings','/api/electives/applications','/api/electives/department/applications/guessed/approve','/api/admin/electives/applications'];
for(const c of [anon,applicant,admin])for(const path of paths){const r=await c.request.post(root+path,{data:{action:'approve'},headers:{origin:root,'x-middleware-subrequest':'middleware:middleware:middleware:middleware:middleware'}});assert.equal(r.status(),403,path);assert.equal((await r.json()).code,'PILOT_NOT_ENABLED');}
for(const path of ['/api/clinical-rotations/hospital/applications','/api/admin/clinical-rotations/applications']){const r=await admin.request.post(root+path,{data:{action:'approve'},headers:{origin:root}});assert.equal(r.status(),403);}
const cancel=await anon.request.post(root+'/api/clinical-rotations/cancellations',{data:{},headers:{origin:root}});assert([401,403].includes(cancel.status()));assert.notEqual((await cancel.json()).code,'PILOT_NOT_ENABLED');
const cleanup=await anon.request.get(root+'/api/internal/clinical-rotations/cleanup');assert.equal(cleanup.status(),403);
console.log('PASS 30 guarded HTTP writes, admin cannot bypass gate; cancellation still authenticated; cleanup fails closed');assert.equal(external,0);console.log('PASS zero external browser requests');
}finally{await browser.close();}
