'use client';
import Link from 'next/link';
import { InstrumentGrid } from './instrument-grid';
import { DepartmentScores } from './department-scores';
import { exploratoryInstrument, mspiStatus } from '@/lib/career-fit/instruments';
import { useEffect, useRef, useState } from 'react';
import { availability, considerations, dimensions, DISCLAIMER, IMA, pathwayLabels, profiles, questions, scale, scoredDimensions, sections, unprofiledBase, VERSION, type Dimension } from '@/lib/career-fit/config';
import { catalogProfile, matchDepartments, matchSpecialties, type Answers, type Catalog, type Factor, type Preference, type Priorities } from '@/lib/career-fit/scoring';
const button='inline-flex min-h-[44px] items-center justify-center rounded-xl border border-brand-200 bg-white px-4 py-2 font-semibold text-brand-800 hover:bg-brand-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-700 disabled:opacity-40';
const primary=button+' !bg-brand-700 !text-white';
const panel='rounded-2xl border border-brand-100 bg-white p-5 shadow-panel sm:p-7';
const field='mt-2 min-h-[44px] w-full rounded-xl border border-slate-300 bg-white p-2 text-ink';
const names:Record<Factor,string>={region:'אזור',hospital:'מוסד',type:'סוג מסגרת'};
const types:Record<string,string>={HOSPITAL:'בית חולים',HMO:'קופת חולים'};
export function CareerFitClient({direct=false}:{direct?:boolean}) {
 const [stage,setStage]=useState(direct?'departments':'intro');
 const [page,setPage]=useState(0);
 const [answers,setAnswers]=useState<Answers>({});
 const [priorities,setPriorities]=useState<Priorities>({});
 const [investigate,setInvestigate]=useState<string[]>([]);
 const [catalog,setCatalog]=useState<Catalog|null>(null);
 const [error,setError]=useState(false);
 const [attempt,setAttempt]=useState(0);
 const [specialty,setSpecialty]=useState('');
 const [preferences,setPreferences]=useState<Preference[]>([]);
 const [unsupported,setUnsupported]=useState<string[]>([]);
 const [compare,setCompare]=useState<string[]>([]);
 const [departmentSort,setDepartmentSort]=useState('personal');
 const [expanded,setExpanded]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{const controller=new AbortController();setError(false);fetch('/api/career-fit/catalog',{signal:controller.signal,credentials:'omit',cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('catalog');const data=await r.json();if(data.version!==VERSION||!Array.isArray(data.departments)||!Array.isArray(data.specialties))throw Error('catalog');setCatalog(data);}).catch(e=>{if(e.name!=='AbortError')setError(true);});return()=>controller.abort();},[attempt]);
 useEffect(()=>{heading.current?.focus({preventScroll:true});window.scrollTo(0,0);},[stage,page]);
 const move=(s:string)=>{setStage(s);setExpanded(false);};
 const reset=()=>{setAnswers({});setPriorities({});setInvestigate([]);setPreferences([]);setUnsupported([]);setCompare([]);setSpecialty('');setPage(0);move(direct?'departments':'intro');};
 const result=matchSpecialties(answers,priorities);
 const subset=catalog?.departments.filter(d=>d.specialtyId===specialty)??[];
 const departmentResult=matchDepartments(subset,preferences);
 const selectedProfile=catalogProfile(catalog?.specialties.find(s=>s.id===specialty)?.name??'');
 const changePreference=(factor:Factor,patch:Partial<Preference>)=>setPreferences(old=>[...old.filter(p=>p.factor!==factor),{factor,values:[],hard:false,weight:1,...old.find(p=>p.factor===factor),...patch}]);
 const toggle=(list:string[],value:string)=>list.includes(value)?list.filter(x=>x!==value):[...list,value];
 const title=stage==='intro'?'בחירת התמחות — מתחילים במה שחשוב לך':stage==='departments'?'אילו מחלקות מתאימות למה שחשוב לי?':stage==='results'?'כיוונים שכדאי לבדוק':stage==='priorities'?'מה חשוב לי יותר?':'איזה תחום מתאים להעדפות שלי?';
 function continueWith(id:string) {const profile=profiles.find(p=>p.id===id)!;const match=catalog?.specialties.find(s=>catalogProfile(s.name)?.id===profile.id);setSpecialty(match?.id??'');setPreferences([]);setCompare([]);move('departments');}
 const summary=<div className="grid gap-2 sm:grid-cols-2">{Object.entries(result.summary).filter(([,v])=>v.value!==null).map(([d,v])=><p key={d}>{dimensions[d as Dimension]}: <strong>{scale[Math.round(v.value!*4)]}</strong> <span className="text-sm text-slate-500">({v.count} תשובות)</span></p>)}</div>;
 return <main dir="rtl" className="mx-auto max-w-5xl space-y-6 px-4 py-8 text-right leading-7">
  <div className="flex flex-wrap items-center justify-between gap-3"><span className="rounded-full bg-teal-50 px-3 py-1 text-sm font-bold text-brand-800">בטא להיכרות עם העדפות</span><button className={button} onClick={reset}>מחק את התשובות שלי והתחל מחדש</button></div>
  <h1 ref={heading} tabIndex={-1} className="text-3xl font-black text-ink outline-none sm:text-4xl">{title}</h1>
  <p className="text-sm text-slate-600">{DISCLAIMER}</p>
  <p className="text-sm text-slate-600">התשובות נשארות בזיכרון הדף בלבד ונמחקות ברענון או בעזיבה. אין צורך בהתחברות. <Link prefetch={false} className="font-semibold text-brand-700 underline" href="/career-fit/methodology">מקורות, שיטה ומגבלות</Link></p>
  {stage==='intro'&&<section className={panel}><h2 className="text-xl font-bold">מסלול MSPI — שילוב כלי מתוקף עדיין ממתין</h2><p>טרם הוסדרו הגרסה, הרשאות השימוש, הניקוד וגרסה עברית מתוקפת. השאלון המקורי למטה הוא כלי חקר נפרד, ולא MSPI. אין כעת שאלון מתוקף באתר.</p><a className="inline-flex min-h-[44px] items-center font-bold text-brand-700 underline" href={mspiStatus.url} target="_blank" rel="noreferrer">למידע ולהערכה הרשמית באתר AAMC (באנגלית; הגישה עשויה להיות מוגבלת)</a><p><Link className="underline" href="/career-fit/methodology#instrument-status">גרסאות, מחקר וזכויות שימוש</Link></p></section>}
  {stage==='intro'&&<div className="grid gap-5 sm:grid-cols-2"><section className={panel}><h2 className="text-2xl font-bold">איזה תחום מתאים להעדפות שלי?</h2><p className="my-4">28 שאלות מקוריות ולא מתוקפות על העבודה שתרצו לעשות, ולא על היכולת שלכם. אפשר לדלג, לחזור ולשנות. אין תשובה נכונה.</p><button className={primary} onClick={()=>move('questions')}>להתחלת השאלון</button></section><section className={panel}><h2 className="text-2xl font-bold">כבר יש לי תחום בראש</h2><p className="my-4">אפשר לעבור ישירות להעדפות מחלקה, לפי המידע הציבורי שכבר קיים באתר.</p><button className={button} onClick={()=>move('departments')}>ישירות להעדפות מחלקה</button></section></div>}
  {stage==='questions'&&<>
   <section className="rounded-xl border border-brand-100 bg-white p-3"><p>חלק {page+1} מתוך 4 · {sections[page]}</p><label htmlFor="progress" className="text-sm">{questions.filter(q=>typeof answers[q.id]==='number').length} מתוך 28 שאלות עם העדפה ידועה</label><progress id="progress" max={28} value={questions.filter(q=>typeof answers[q.id]==='number').length} className="my-2 block h-2 w-full accent-teal-700"/><p className="text-sm text-slate-600">אפשר לרצות גם טיפול חריף וגם מעקב, או גם קשר עם מטופלים וגם פעולות. ״לא יודע/ת״ אינו אמצע הסולם.</p></section>
   <InstrumentGrid instrument={exploratoryInstrument} section={page} answers={answers} onAnswer={(id,value)=>setAnswers(a=>{const next={...a};if(value===undefined)delete next[id];else next[id]=value;return next;})}/>

   <div className="flex flex-wrap gap-3"><button className={button} onClick={()=>page?setPage(page-1):move('intro')}>חזרה</button><button className={primary} onClick={()=>page<3?setPage(page+1):move('priorities')}>המשך</button><button className={button} onClick={()=>move('results')}>סיכום ביניים</button></div>
  </>}
  {stage==='priorities'&&<section className={panel}><p className="mb-5">עד כמה כל העדפה חשובה להשוואה? החשיבות נפרדת ממידת העניין. ברירת המחדל שווה לכל הממדים, ללא תלות במספר השאלות.</p><div className="grid gap-4 sm:grid-cols-2">{scoredDimensions.map(d=><label key={d}>{dimensions[d]}<select className={field} value={priorities[d]??1} onChange={e=>setPriorities(p=>({...p,[d]:Number(e.target.value)}))}>{['לא לשקלל','חשיבות רגילה','חשוב לי','חשוב לי במיוחד'].map((s,i)=><option key={i} value={i}>{s}</option>)}</select></label>)}</div><fieldset className="my-6"><legend className="font-bold">שיקולים נוספים לבירור — אינם משנים את ההצעות</legend><p>מחקר והוראה אפשריים בתחומים רבים. אין כאן בסיס לקבוע שכר, שעות או סיכויי קבלה לפי תחום.</p><div className="mt-3 flex flex-wrap gap-4">{considerations.map(c=><label key={c} className="flex min-h-[44px] items-center gap-2"><input type="checkbox" checked={investigate.includes(c)} onChange={()=>setInvestigate(toggle(investigate,c))}/>{c}</label>)}</div></fieldset><div className="flex gap-3"><button className={button} onClick={()=>move('questions')}>חזרה לשאלות</button><button className={primary} onClick={()=>move('results')}>להצגת הכיוונים</button></div></section>}
  {stage==='results'&&<>
   <section className={panel}><h2 className="mb-3 text-xl font-bold">סיכום ההעדפות שלך</h2>{summary}<p className="mt-3">לבירור נוסף, ללא שקלול: {investigate.join(' · ')||'לא סומנו שיקולים נוספים'}. מחקר והוראה נשמרים בסיכום בלבד.</p><div className="mt-4 flex flex-wrap gap-3"><button className={button} onClick={()=>{setPage(0);move('questions');}}>עריכת תשובות</button><button className={button} onClick={()=>move('priorities')}>השוואה ועריכת סדרי עדיפויות</button></div></section>
   {!result.sufficient||result.suggestions.length===0?<section role="status" className={panel}><h2 className="text-xl font-bold">אין עדיין מידע מספיק להצעת כיוונים</h2><p>כדאי להשלים לפחות 10 תשובות ב־6 ממדים, ולברר עוד פעילויות שמעניינות אותך. גם עם תשובות רבות, אפיון התחומים עשוי להיות חלקי מדי. אפשר להמשיך לחיפוש מחלקות בכל תחום.</p></section>:<><p>נמצאו {result.suggestions.length} כיוונים לבדיקה. הראיות החלקיות אינן מאפשרות להכריע ביניהם; הסדר אלפביתי בלבד. אלה אינם ציוני התאמה או תחזית הצלחה.</p>{result.suggestions.slice(0,expanded?undefined:5).map(r=><article key={r.profile.id} className={panel}><h2 className="text-2xl font-bold">{r.profile.label}</h2><p className="text-sm font-semibold text-brand-800">{r.profile.pathways.map(p=>pathwayLabels[p]).join(' · ')}</p>{r.profile.id==='psychiatry'&&<p>קיים גם מסלול למומחים ברפואת משפחה; תנאיו במקור הרשמי.</p>}<p className="mt-3">למה הופיע: {r.positive.map(c=>`${dimensions[c.dimension]} (העדפה ${Math.round(c.value*4*10)/10}/4; חשיבות ${c.weight})`).join(' · ')}.</p><p className="mt-3 text-sm">{r.profile.interpretation}</p><p className="mt-3 text-sm">נקודות לבירור: {r.contributions.filter(c=>c.value<.5).map(c=>`${dimensions[c.dimension]} — סימנת עניין נמוך`).join(' · ')||'איך הפעילויות שמעניינות אותך משתלבות ביום עבודה בפועל?'}.</p><p className="text-sm text-slate-600">כיסוי: {r.contributions.length} מתוך {scoredDimensions.filter(d=>result.summary[d].value!==null&&(priorities[d]??1)>0).length} ממדים פעילים. חסר אפיון: {r.unknown.map(d=>dimensions[d]).join(' · ')||'אין בממדים שנענו'}. {r.profile.limitation}</p><details className="my-3 text-sm"><summary className="cursor-pointer font-semibold">פירוט החישוב והמקור</summary>{r.contributions.map(c=><p key={c.dimension}>{dimensions[c.dimension]}: העדפה {c.value*4}/4 × חשיבות {c.weight}; תרומה פנימית {c.contribution.toFixed(3)} (אינה אחוז התאמה).</p>)}<a className="text-brand-700 underline" href={r.profile.sources[0]} target="_blank" rel="noreferrer">המסלול הרשמי בהר״י</a> · <Link prefetch={false} className="underline" href="/career-fit/methodology">שיטת החישוב</Link></details><button className={primary} onClick={()=>continueWith(r.profile.id)}>למחלקות ולהעדפות בתחום</button></article>)}{result.suggestions.length>5&&<button className={button} onClick={()=>setExpanded(!expanded)}>{expanded?'הצג פחות':`הצג את כל ${result.suggestions.length} הכיוונים ללא הכרעה`}</button>}</>}
   <details className={panel}><summary className="cursor-pointer font-bold">תחומים שלא אופיינו או שאין מספיק מידע לגביהם</summary><p>אי־הופעה אינה אי־התאמה. מקצועות בסיס ללא פרופיל: {unprofiledBase.join(' · ')}.</p><p>פרופילים חלקיים שלא עברו את סף המידע בהעדפות הנוכחיות: {result.evaluated.filter(r=>!r.eligible).map(r=>r.profile.label).join(' · ')||'אין'}.</p><p>קטגוריות קטלוג ללא מיפוי: {catalog?.specialties.filter(s=>!catalogProfile(s.name)).map(s=>s.name).join(' · ')||'הקטלוג אינו זמין או שאין קטגוריות נוספות'}.</p><a href={IMA} className="underline">מקצועות בסיס, מקצועות על והשתלמויות עמיתים — הרשימה הרשמית</a></details>
   <button className={button} onClick={()=>move('departments')}>בחירת תחום ידנית והעדפות מחלקה</button>
  </>}
  {stage==='departments'&&<>
   <div className="flex flex-wrap gap-3"><button className={button} onClick={()=>move(Object.keys(answers).length?'results':'intro')}>חזרה להיכרות עם תחומים</button><Link prefetch={false} className={button} href="/departments">חיפוש המחלקות הקיים</Link></div>
   {error?<section role="alert" className={panel}><h2 className="font-bold">לא ניתן לטעון כרגע את נתוני המחלקות</h2><p>לא מוצגות תוצאות חלופיות או נתונים מומצאים. התשובות שלך נשארות בדף.</p><button className={button} onClick={()=>setAttempt(a=>a+1)}>נסה/י שוב</button></section>:!catalog?<p role="status">טוענים את הקטלוג הציבורי…</p>:<>
    <section className={panel}><label className="font-bold">תחום בקטלוג המחלקות<select className={field} value={specialty} onChange={e=>{setSpecialty(e.target.value);setPreferences([]);setCompare([]);}}><option value="">בחר/י תחום</option>{catalog.specialties.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><p className="mt-3 text-sm">קטגוריית מחלקה אינה מסלול הכשרה. {selectedProfile?selectedProfile.pathways.map(p=>pathwayLabels[p]).join(' · '):'סיווג המסלול לא אומת כאן; יש לבדוק את תנאי המסלול ברשימת הר״י.'} <a className="underline" href={IMA}>למסלולים הרשמיים</a></p>{!catalog.specialties.length&&<p role="status">אין כרגע מחלקות זמינות בקטלוג הציבורי.</p>}</section>
    {specialty&&<>
     <section className={panel}><h2 className="text-xl font-bold">העדפות, תנאי חובה ומידע חסר</h2><p className="my-3">רק תנאי שסימנת כחובה יכול להוציא מחלקה. העדפה רכה משנה סדר רק כאשר כל הנתונים שנבחרו ידועים.</p><div className="space-y-5">{(['region','hospital','type'] as Factor[]).map(f=>{const pref=preferences.find(p=>p.factor===f);const options=Array.from(new Set(subset.map(d=>d[f]).filter((s):s is string=>s!==null))).sort();return <fieldset key={f} className="rounded-xl border border-slate-200 p-4"><legend className="px-2 font-bold">{names[f]}</legend><label>ערך מועדף<select className={field} value={pref?.values[0]??''} onChange={e=>changePreference(f,{values:e.target.value?[e.target.value]:[]})}><option value="">ללא העדפה</option>{options.map(o=><option key={o} value={o}>{f==='hospital'?subset.find(d=>d.hospital===o)?.hospitalName:f==='type'?types[o]??o:o}</option>)}</select></label><div className="mt-3 flex flex-wrap items-center gap-4"><label className="flex min-h-[44px] items-center gap-2"><input type="checkbox" checked={pref?.hard??false} onChange={e=>changePreference(f,{hard:e.target.checked})}/>תנאי חובה מפורש</label><label>חשיבות ההעדפה<select className="mx-2 min-h-[44px] rounded-lg border p-2" disabled={pref?.hard} value={pref?.weight??1} onChange={e=>changePreference(f,{weight:Number(e.target.value)})}><option value={0}>לא לשקלל</option><option value={1}>רגילה</option><option value={2}>חשוב</option><option value={3}>חשוב במיוחד</option></select></label></div><p className="text-sm text-slate-600">ערך ידוע ב־{subset.filter(d=>d[f]!==null).length} מתוך {subset.length} מחלקות. {availability.find(a=>a.id===f)?.meaning}</p></fieldset>;})}</div>
     <fieldset className="mt-5"><legend className="font-bold">עוד דברים שחשובים לי</legend>{availability.filter(a=>!a.supported).map(a=><div key={a.id} className="mt-3"><label className="flex min-h-[44px] items-center gap-2"><input type="checkbox" checked={unsupported.includes(a.id)} onChange={()=>setUnsupported(toggle(unsupported,a.id))}/>{a.label}</label><p className="text-sm text-slate-600">אין כרגע מידע מספיק להשוואה לפי העדפה זו — לא נכלל בחישוב.</p></div>)}</fieldset><button className={button+' mt-4'} onClick={()=>{setPreferences([]);setUnsupported([]);setCompare([]);}}>איפוס העדפות מחלקה</button></section>
     <label>סדר תוצאות<select className={field} value={departmentSort} onChange={e=>setDepartmentSort(e.target.value)}><option value="personal">התאמה אליך</option><option value="name">שם המחלקה</option></select></label><p className="text-sm">מיון לפי מדד המחלקה אינו זמין: אין מספיק מחלקות עם מדד בר־השוואה בתחום.</p>
     <section aria-live="polite" className={panel}><h2 className="text-2xl font-bold">התאמה להעדפות שהגדרת</h2><p>{departmentResult.ranked?'סדר לפי העדפות נתמכות בלבד; ערכים זהים הם תיקו. אין ציון איכות.':'אין בסיס לדירוג לפי העדפות רכות שנבחרו; מוצגות תוצאות סינון ועובדות ידועות.'}</p><p className="text-sm">מקור: קטלוג Hitmachut הציבורי. נטען {new Date(catalog.retrievedAt).toLocaleDateString('he-IL')}; תקופת המדידה ושנת העדכון אינן זמינות. הכיסוי מתייחס לקטלוג הגלוי בלבד.</p>{unsupported.length>0&&<p>לבירור אישי ללא שקלול: {availability.filter(a=>unsupported.includes(a.id)).map(a=>a.label).join(' · ')}.</p>}</section>
     {(['comparable','insufficient','unverified'] as const).map(group=><section key={group} className="space-y-3"><h3 className="text-xl font-bold">{group==='comparable'?'מחלקות עם נתונים להשוואה':group==='insufficient'?'מידע חסר — ללא דירוג':'תנאי חובה שטרם אומתו'} ({departmentResult[group].length})</h3>{!departmentResult[group].length&&<p className="text-sm text-slate-600">אין מחלקות בקבוצה זו בהגדרות הנוכחיות.</p>}{[...departmentResult[group]].sort((a,b)=>departmentSort==='name'?a.department.name.localeCompare(b.department.name,'he'):0).map(r=><article key={r.department.id} className={panel}><h4 className="text-lg font-bold">{r.department.name} · {r.department.hospitalName}</h4><DepartmentScores department={r.department} row={r}/><p>אזור: {r.department.region??'לא ידוע'} · מסגרת: {types[r.department.type??'']??'לא ידוע'}</p>{r.score!==null&&departmentResult.comparable.filter(o=>o.score===r.score).length>1&&<p className="text-sm font-bold text-brand-800">תיקו בהעדפות הנתמכות</p>}{r.facts.map(f=><p key={f.factor} className="text-sm">{names[f.factor]}: {f.value===null?'לא ידוע':f.factor==='hospital'?r.department.hospitalName:f.factor==='type'?types[f.value]:f.value} — {f.matches===null?'לא אומת':f.matches?'תואם':'אינו תואם'} {f.hard?'לתנאי החובה':`להעדפה (חשיבות ${f.weight})`}</p>)}<p className="mt-2 text-sm text-slate-600">חסר בסיס השוואה: חשיפה, מחקר, גודל צוות, הוראה וסביבת עבודה{r.facts.some(f=>f.value===null)?' וגם '+r.facts.filter(f=>f.value===null).map(f=>names[f.factor]).join(', '):''}. נתונים חסרים אינם מעידים על איכות נמוכה.</p><div className="mt-3 flex flex-wrap items-center gap-4"><Link prefetch={false} className="font-bold text-brand-700 underline" href={`/departments/${r.department.slug}`}>לעמוד המחלקה ולמקורות</Link><label className="flex min-h-[44px] items-center gap-2"><input type="checkbox" disabled={!compare.includes(r.department.id)&&compare.length>=4} checked={compare.includes(r.department.id)} onChange={()=>setCompare(toggle(compare,r.department.id))}/>בחירה להשוואה</label></div></article>)}</section>)}
     <details className={panel}><summary className="cursor-pointer">לא עומדות בתנאי חובה ידוע ({departmentResult.excluded.length})</summary>{departmentResult.excluded.map(r=><p key={r.department.id}>{r.department.name} · {r.department.hospitalName}: {r.facts.filter(f=>f.hard&&f.matches===false).map(f=>`${names[f.factor]}: ${f.factor==='hospital'?r.department.hospitalName:f.factor==='type'?types[f.value!]:f.value}`).join(' · ')}</p>)}</details>
     {compare.length>0&&<Link prefetch={false} className={primary} href={`/compare?${new URLSearchParams({specialty,departments:compare.join(',')})}`}>השוואת {compare.length} מחלקות — נדרשת התחברות</Link>}
    </>}
   </>}
  </>}
 </main>;
}
