'use client';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {CareerJourney} from './career-journey';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Card} from '@/components/ui/card';
import {EvidenceAttribution} from './evidence-sources';
import {RIASEC,interestLabels,itemsFor,sectionsFor,interestChoices,importanceChoices,fitDisclaimer,crosswalk,type Mode,type AnswerMap} from '@/lib/career-fit/evidence/model';
import {explainSpecialty} from '@/lib/career-fit/evidence/explanation';
import {answered,rankSpecialties} from '@/lib/career-fit/evidence/scoring';
import {makeDraft,completion,jump,respond,next,readDraft,saveDraft,clearDraft,type Draft} from '@/lib/career-fit/evidence/draft';
const focus='min-h-[48px] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-brand-700 motion-reduce:transition-none';
const link='inline-flex min-h-[44px] items-center font-semibold text-brand-700 underline underline-offset-4 focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand-700';
function Band({label,value,text}:{label:string;value:number|null;text:string}) {
 return <div className="space-y-2"><div className="flex justify-between gap-3 text-sm"><span>{label}</span><bdi className="shrink-0 font-semibold">{text}</bdi></div>{value===null?<p className="text-xs text-slate-600">חסר מידע — לא חושב ציון</p>:<div role="meter" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(value*100)} aria-valuetext={text} className="h-2 overflow-hidden rounded-full bg-brand-50"><div className="h-full rounded-full bg-teal-700" style={{width:`${Math.max(0,Math.min(100,value*100))}%`}}/></div>}</div>;
}
export function EvidenceQuestionnaire() {
 const router=useRouter();
 const [draft,setDraft]=useState<Draft|null>(null),[consent,setConsent]=useState(false),[ready,setReady]=useState(false),[saveError,setSaveError]=useState(false);
 const mobileNavigation=useRef<HTMLDetailsElement>(null);
 const heading=useRef<HTMLHeadingElement>(null),question=useRef<HTMLHeadingElement>(null),progress=useRef<HTMLElement>(null);
 const mode=draft?.mode??null,index=draft?.index??0,answers=draft?.answers??{},stage=draft?.stage??'intro';
 const items=mode?itemsFor(mode):[],item=items[index],sections=mode?sectionsFor(mode):[];
 useEffect(()=>{try{setDraft(readDraft(window.localStorage));}catch{setSaveError(true);}setReady(true);},[]);
 useEffect(()=>{if(!ready)return;const target=stage==='questions'?question.current:heading.current;target?.focus({preventScroll:true});(stage==='questions'?progress.current:target)?.scrollIntoView({block:'start',behavior:'instant'});},[stage,index,ready]);
 const update=(value:Draft)=>{setDraft(value);try{saveDraft(window.localStorage,value);setSaveError(false);}catch{setSaveError(true);}};
 const start=()=>{if(consent)update(makeDraft('quick'));};
 const reset=()=>{try{clearDraft(window.localStorage);setSaveError(false);}catch{setSaveError(true);}setDraft(null);setConsent(false);};
 const navigate=(position:number)=>{if(mobileNavigation.current)mobileNavigation.current.open=false;if(draft)update(jump(draft,position));};
 const currentSection=sections.findIndex(s=>index>=s.start&&index<s.end);
 const overview=<ol className="space-y-3">{sections.map((s,i)=>{const done=items.slice(s.start,s.end).filter(q=>answered(q,answers)).length;return <li key={s.id} className={`rounded-xl border p-3 text-sm ${i===currentSection?'border-brand-200 bg-brand-50 text-brand-900':'border-slate-100 text-slate-600'}`}><button type="button" aria-current={i===currentSection?'step':undefined} className={`${focus} w-full text-right font-semibold`} onClick={()=>navigate(s.start)}>{done===s.end-s.start?'✓':i+1}. {s.label}<span className="block text-xs font-normal">{done} מתוך {s.end-s.start} נענו</span></button><div className="mt-2 grid grid-cols-5 gap-1">{items.slice(s.start,s.end).map((q,n)=>{const position=s.start+n,done=answered(q,answers),skipped=draft?.skipped.includes(q.id),status=done?'נענתה':skipped?'דולגה':'טרם נענתה';return <button type="button" key={q.id} aria-label={`שאלה ${position+1} · ${status}`} aria-current={position===index?'step':undefined} className={`min-h-[44px] rounded-lg border text-xs focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-700 ${position===index?'border-brand-900 bg-brand-800 font-bold text-white':done?'border-teal-700 bg-teal-50 text-teal-900':skipped?'border-dashed border-slate-500 bg-white':'border-slate-300 bg-white'}`} onClick={()=>navigate(position)}>{position+1}<span aria-hidden="true" className="block leading-3">{done?'✓':skipped?'↷':'○'}</span></button>;})}</div></li>;})}</ol>;
 if(!ready)return <main dir="rtl" className="mx-auto max-w-6xl p-8" role="status">טוענים את השאלון השמור…</main>;
 return <main dir="rtl" className="mx-auto max-w-6xl space-y-6 px-4 py-8 text-right leading-7">
  <div className="flex flex-wrap items-center justify-between gap-3">{stage!=='intro'&&<Button variant="secondary" className={focus} onClick={reset}>מחיקת התשובות והתחלה מחדש</Button>}</div>
  <h1 ref={heading} tabIndex={-1} className="scroll-mt-36 text-3xl font-black text-ink outline-none sm:text-4xl">{stage==='intro'?'מצאו את ההתמחות שמתאימה לכם':stage==='questions'?'שאלון התאמה להתמחות':stage==='review'?'סיימתם כמעט הכל':'ההתמחויות שהכי מתאימות לפרופיל שלכם'}</h1>
  {saveError&&<p role="alert" className="rounded-xl border border-amber-300 bg-amber-50 p-3">השמירה המקומית אינה זמינה. תשובות חדשות יישמרו רק עד סגירת הדף. אם המחיקה נכשלה, יש למחוק את נתוני האתר בהגדרות הדפדפן.</p>}
  {draft&&!saveError&&<p role="status" className="text-xs text-slate-600">התשובות נשמרות אוטומטית במכשיר זה למשך עד 30 יום. במכשיר משותף מומלץ למחוק אותן בסיום.</p>}
  {stage==='intro'&&<>
   <p className="max-w-3xl text-lg text-slate-600">כלי עזר מבוסס שאלוני עניין והעדפות, לבחינת כיווני התמחות ולהמשך בירור בשטח.</p>
   <label className="flex min-h-[48px] cursor-pointer items-start gap-3 rounded-lg p-2 text-sm has-[:focus-visible]:outline has-[:focus-visible]:outline-2 has-[:focus-visible]:outline-brand-700"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-2 h-5 w-5 shrink-0 accent-brand-700"/><span>קראתי והבנתי כי תוצאות השאלון הן כלי עזר לקבלת החלטה ואינן מהוות הבטחה להתאמה או לקבלה להתמחות.</span></label>
   <CareerJourney onStart={start} startDisabled={!consent} onDepartments={()=>router.push('/career-fit/departments')}/>
   <section aria-label="על השאלון" className="space-y-2 rounded-xl border border-brand-100 bg-white/70 p-4 text-sm text-slate-600"><h2 className="font-bold text-ink">על השאלון</h2><p>השאלון כולל 30 שאלות על סוג העבודה הרפואית שמושך אתכם, ומבוסס על מודל תחומי העניין RIASEC בהתאמה להקשר רפואי. הניסוחים הותאמו לעברית בסיוע כלי בינה מלאכותית. זהו כלי עזר לבחינת העדפות, ולא כלי פסיכומטרי מאומת או הבטחה להתאמה להתמחות.</p><p>התשובות נשמרות במכשיר זה עד 30 יום מהשינוי האחרון, ללא שליחתן לשרת. אפשר למחוק אותן בכל עת.</p><Link className={link} href="/career-fit/sources">מקורות, שיטה ומגבלות</Link></section>

  </>}
  {stage==='questions'&&item&&<>
   <section ref={progress} aria-label="התקדמות" className="scroll-mt-36 rounded-2xl border border-brand-100 bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><p className="font-semibold text-brand-800">שלב {currentSection+1} מתוך {sections.length} · {sections[currentSection]?.label}</p><p>שאלה {index+1} מתוך {items.length}</p></div><progress aria-label="שאלות שנענו" value={items.filter(q=>answered(q,answers)).length} max={items.length} className="my-3 block h-2 w-full overflow-hidden rounded-full accent-teal-700 [&::-webkit-progress-bar]:bg-brand-50 [&::-webkit-progress-value]:bg-teal-700 [&::-moz-progress-bar]:bg-teal-700"/><p className="text-xs text-slate-600">{items.filter(q=>answered(q,answers)).length} נענו · דילוג נשאר כחסר מידע</p></section>
   <div className="grid items-start gap-6 lg:grid-cols-[230px_minmax(0,1fr)]"><aside aria-label="שלבי השאלון" className="sticky top-28 hidden max-h-[calc(100vh-9rem)] overflow-y-auto rounded-2xl border border-brand-100 bg-white p-3 lg:block">{overview}</aside><div className="min-w-0 space-y-4"><details ref={mobileNavigation} className="rounded-xl border bg-white px-4 lg:hidden"><summary className="cursor-pointer py-3 font-semibold focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand-700"><span aria-hidden="true" className="me-2 inline-block text-brand-700">⌄</span>כל השאלות</summary>{overview}</details>
    <Card className="!bg-white !p-5 sm:!p-7">
     <p className="mb-3 text-sm font-semibold text-teal-800">{item.dimension?'סוג העבודה הרפואית שמושך אתכם':'שיקולים בבחירת ההתמחות שלכם'}</p>
     <fieldset aria-describedby="question-help"><legend className="w-full"><h2 ref={question} tabIndex={-1} className="scroll-mt-36 text-2xl font-bold leading-9 text-ink outline-none">{item.hebrew}</h2></legend><p id="question-help" className="mb-5 mt-3 text-sm text-slate-600">{!item.dimension?'בחרו תשובה אחת לפי החשיבות עבורכם. ניסיון או ידע שעדיין חסרים אפשר להשאיר ללא תשובה.':'חשבו על סוג העבודה הרפואית שמעניין אתכם, ולא על מידת הניסיון שלכם כיום. ״לא בטוח/ה״ הוא אמצע הסולם; דילוג נשאר ללא ציון.'}</p>{item.helper&&<p className="mb-4 rounded-lg border border-brand-100 bg-brand-50 p-3 text-sm">{item.helper}</p>}
      <div className="grid gap-3 sm:grid-cols-2">{(!item.dimension?importanceChoices:interestChoices).map((label,i)=>{const value=i+(!item.dimension?1:0),selected=answers[item.id]===value;return <label key={value} className={`flex min-h-[64px] cursor-pointer items-center gap-3 rounded-xl border-2 px-4 py-3 transition-colors motion-reduce:transition-none has-[:focus-visible]:outline has-[:focus-visible]:outline-2 has-[:focus-visible]:outline-offset-2 has-[:focus-visible]:outline-brand-700 ${selected?'border-brand-700 bg-brand-50 font-semibold text-brand-900':'border-slate-200 text-slate-700 hover:border-brand-300 hover:bg-brand-50'}`}><input className="sr-only" type="radio" name={item.id} value={value} checked={selected} onChange={()=>draft&&update(respond(draft,value))}/><span aria-hidden="true" className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full border ${selected?'border-brand-700 bg-brand-700 text-white':'border-slate-500'}`}>{selected?'✓':''}</span>{label}</label>;})}</div>
     </fieldset>
     <div className="mt-5 flex flex-col gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:justify-between"><Button variant="secondary" className={focus} disabled={index===0} onClick={()=>navigate(index-1)}>חזרה</Button><Button className={`${focus} sm:min-w-[180px]`} onClick={()=>draft&&update(next(draft))}>{index===items.length-1?'לבדיקת התשובות':'המשך'}</Button></div>
     <div className="mt-3 flex flex-wrap justify-between gap-3"><button className={link} type="button" onClick={()=>draft&&update(next(respond(draft,null)))}>דלג כרגע</button><button className={link} type="button" onClick={()=>draft&&update({...draft,stage:'review'})}>בדיקת התשובות</button></div>
     <details className="mt-4 text-xs text-slate-600"><summary className="cursor-pointer py-2 focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand-700"><span aria-hidden="true" className="me-2 inline-block text-brand-700">⌄</span>המקור והתרגום של הפריט</summary><p dir="ltr" className="text-left">{item.english}</p><p dir="ltr" className="text-left">{item.source} · {item.sourceItemId} · {item.sourceLocator}</p><p>ניסוח מקורי או התאמה לעברית בסיוע AI; טרם נערכה בדיקה אנושית מקצועית וטרם בוצע תיקוף. <Link className="underline" href="/career-fit/sources">פירוט ההתאמות והמקורות</Link></p></details>
    </Card>
   </div></div>
  </>}
  {stage==='review'&&draft&&(()=>{const review=completion(draft);return <Card className="space-y-5 !bg-white"><p className="text-xl">עניתם על {review.answered} מתוך {items.length} שאלות.</p><p>✓ {review.answered} נענו · ○ {review.missing.length} טרם נענו</p><p className="text-sm text-slate-600">כל 30 שאלות תחומי העניין נדרשות לדירוג. תשובות חסרות אינן מוחלפות בתשובה ניטרלית.</p>{review.missing.length>0&&<><Button className={focus} onClick={()=>navigate(items.findIndex(i=>i.id===review.missing[0].id))}>השלימו {review.missing.length} שאלות</Button><ul className="space-y-2">{review.missing.map(q=><li key={q.id}><button type="button" className={`${link} text-right`} onClick={()=>navigate(items.findIndex(i=>i.id===q.id))}>{items.findIndex(i=>i.id===q.id)+1}. {q.hebrew} {q.dimension?'(נדרשת לדירוג)':'(רשות)'}</button></li>)}</ul></>}<p role="status">{review.coreMissing.length?`חסרות ${review.coreMissing.length} תשובות ליבה לחישוב המדד.`:'כל שאלות הליבה נענו.'}</p><div className="flex flex-col gap-3 sm:flex-row"><Button className={focus} disabled={!review.canSubmit} onClick={()=>review.canSubmit&&update({...draft,stage:'results'})}>צפו בתוצאות שלי</Button><Button variant="secondary" className={focus} onClick={()=>navigate(index)}>חזרה לשאלון</Button></div></Card>;})()}
  {stage==='results'&&mode&&<EvidenceResults mode={mode} answers={answers} onEdit={()=>navigate(0)}/>}

 </main>;
}
function EvidenceResults({mode,answers,onEdit}:{mode:Mode;answers:AnswerMap;onEdit:()=>void}) {
 const result=rankSpecialties(mode,answers),top=result.ranked.filter(r=>r.correlation>=0).slice(0,3);
 return <div className="space-y-6">
  <p className="text-slate-600">{fitDisclaimer} הפריטים הרפואיים מקוריים וטרם הוכחה שקילותם לתחומי העניין במקור האמריקאי. ההשוואה ניסיונית ומוגבלת ל־17 תחומים בעלי מיפוי ישיר; אינה כוללת את כל ההתמחויות.</p>
  <div className="flex flex-wrap gap-3"><Button variant="secondary" className={focus} onClick={onEdit}>חזרה לתשובות ולהשלמה</Button><Link href="/career-fit/departments" className={link}>להעדפות מחלקה</Link></div>
  {result.status!=='READY'?<Card role="status"><h2 className="text-xl font-bold">{result.status==='INCOMPLETE'?'חסרות תשובות לחישוב מדד התאמה':'אין עדיין הבדלים בין תחומי העניין שלכם'}</h2><p className="mt-3">{result.status==='INCOMPLETE'?'נדרשות תשובות לכל פריטי תחומי העניין. לא משלימים תשובות חסרות ולא מחשבים ציון חלקי.':'כשכל ששת התחומים מקבלים אותו ציון, לא ניתן לחשב מתאם. אפשר לעיין בתשובות; אין צורך לשנות תשובה רק כדי לקבל דירוג.'}</p></Card>:<>
   <section aria-label="שלושת הכיוונים המובילים" className="space-y-3"><h2 className="text-xl font-bold">כיוונים בולטים להמשך בירור</h2><p className="text-sm text-slate-600">הציונים הגבוהים מבין התחומים שמופו, לא הבטחה להתאמה. ציונים מעוגלים זהים אינם מעידים על הבדל משמעותי.</p>{top.length?<div className="grid gap-4 md:grid-cols-3">{top.map(r=><Card key={r.specialty.code} className="!border-brand-200 !bg-white"><h3 className="text-xl font-bold">{r.specialty.specialty}</h3><p className="my-4 text-4xl font-black text-brand-800"><bdi>{r.displayIndex}<span className="text-base font-normal">/100</span></bdi></p><p className="text-sm text-slate-600">מדד התאמה לדפוס העניין</p><a className={link} href={`#occupation-${r.specialty.code}`}>לפרטים על ההתאמה</a></Card>)}</div>:<p role="status">לא נמצא מתאם חיובי בין הפרופיל שלכם לתחומים שמופו. אפשר לעיין בכל הערכים ובתחומים שאין להם מיפוי.</p>}</section>
   <section aria-label="כל התחומים בעלי מיפוי ישיר" className="space-y-3"><h2 className="text-xl font-bold">כל התחומים שמופו — לפי מדד התאמה</h2>{result.ranked.map(r=>{const explanation=explainSpecialty(r);return <article id={`occupation-${r.specialty.code}`} key={r.specialty.code} className="scroll-mt-36 rounded-2xl border border-brand-100 bg-white p-4 sm:p-5" aria-label={r.specialty.specialty}>
    <div className="flex items-baseline justify-between gap-4"><h3 className="font-bold text-brand-900">{r.specialty.specialty}</h3><span className="shrink-0 font-bold text-brand-800" aria-label={`מדד התאמה ${r.displayIndex} מתוך 100`}><bdi>{r.displayIndex}/100</bdi></span></div>
    <div className="mb-4 mt-3 h-2 overflow-hidden rounded-full bg-brand-50" aria-hidden="true"><div className="h-full rounded-full bg-teal-700" style={{width:`${r.index}%`}}/></div>
    <details data-fit-explanation><summary className="flex min-h-[44px] cursor-pointer items-center justify-between gap-3 rounded-lg font-semibold text-brand-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-700">{r.correlation>0?'למה התחום מתאים לך?':'מה דומה ומה שונה בפרופיל שלך?'}<span aria-hidden="true">⌄</span></summary>
    <div className="space-y-4 pt-3">
     <p className="text-xs text-slate-600">נקודות דמיון ושוני בין תחומי העניין שלך לפרופיל התחום. זו השוואה ניסיונית לצורך בירור, לא קביעה שהתחום מתאים לך.</p>
     {explanation.shared.length>0?<ul className="space-y-3 text-sm">{explanation.shared.map(reason=><li key={reason.dimension} className="flex items-start gap-2"><span aria-hidden="true" className="font-bold text-teal-800">✓</span><span>{reason.text}</span></li>)}</ul>:<p className="text-sm">לא נמצאו נקודות דמיון בולטות בפרופילים.</p>}
     {explanation.considerations.length>0&&<div className="space-y-2 border-t border-slate-100 pt-4"><h4 className="font-semibold">כדאי לקחת בחשבון</h4><ul className="space-y-3 text-sm text-slate-700">{explanation.considerations.map(reason=><li key={reason.dimension} className="flex items-start gap-2"><span aria-hidden="true">○</span><span>{reason.text}</span></li>)}</ul></div>}
     <details data-fit-calculation className="rounded-xl border border-brand-100 bg-brand-50/40 p-3 sm:p-4"><summary className="flex min-h-[44px] cursor-pointer items-center justify-between gap-3 rounded-lg font-semibold text-brand-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-700">איך חושב המדד?<span aria-hidden="true">⌄</span></summary><div className="space-y-4 pt-3">
     <h4 className="font-semibold">פרופיל התחום ופרופיל התשובות שלך — RIASEC</h4>
     <p className="text-xs text-slate-600">״יחסי״ מתייחס לממוצע בתוך כל פרופיל. ששת הממדים אינם מודדים קצב עבודה, עצמאות, רצף טיפולי או יכולת קלינית. אין כאן נימוקים על מאפיינים אלה.</p>
     <div className="overflow-x-auto"><table className="w-full text-right text-xs"><caption className="pb-2 text-right font-semibold">הערכים שמרכיבים את המתאם</caption><thead><tr><th className="p-2">תחום</th><th className="p-2">שלכם 0–100</th><th className="p-2">מקצוע 1–7</th><th className="p-2">תרומה למתאם</th></tr></thead><tbody>{r.dimensions.map(d=><tr key={d.dimension} className="border-t border-slate-100"><th className="p-2 font-normal">{interestLabels[d.dimension]}</th><td className="p-2"><bdi>{(d.user*100).toFixed(1)}</bdi></td><td className="p-2"><bdi>{d.occupation.toFixed(2)}</bdi></td><td className="p-2"><bdi>{d.contribution.toFixed(4)}</bdi></td></tr>)}</tbody></table></div>
     <p className="text-xs">מתאם פירסון (Pearson correlation): סכום התרומות = <bdi>{r.correlation.toFixed(4)}</bdi>. מדד = <bdi>50 × (1 + r)</bdi> = <bdi>{r.index.toFixed(2)}</bdi>, מעוגל ל־{r.displayIndex}. הערכים בטבלה מעוגלים; החישוב משתמש בערכים המלאים.</p>
     <p className="text-xs text-slate-600">מיפוי ישיר למקצוע אמריקאי, לא תיקוף של מסלול ישראלי. {['מחלות עיניים','כירורגיה אורתופדית'].includes(r.specialty.specialty)&&'המקצוע במקור אינו כולל רפואת ילדים.'}{r.specialty.specialty==='רפואה פנימית'&&'התיאור האמריקאי מתמקד בעיקר במרפאה, ולא בהכשרה במחלקה בישראל.'}</p>
     <p dir="ltr" className="text-left text-xs text-slate-600"><a className="underline" href={`https://www.onetonline.org/link/summary/${r.specialty.code}`}>{r.specialty.title} · {r.specialty.code}</a> · מקור O*NET31.0 · {r.specialty.sourceDate} · {r.specialty.sourceMethod}</p>
     </div></details>
    </div></details>
   </article>;})}</section>
  </>}
  <Card className="space-y-5"><h2 className="text-2xl font-bold">הפרופיל שלכם</h2><h3 className="font-semibold">ששת תחומי העניין — RIASEC</h3><div className="grid gap-5 sm:grid-cols-2">{RIASEC.map(d=><Band key={d} label={`${d} · ${interestLabels[d]}`} value={result.profile[d].normalized} text={result.profile[d].sum===null?`${result.profile[d].count}/${result.profile[d].total} נענו`:`${result.profile[d].sum}/${result.profile[d].max}`}/>)}</div>

  </Card>
  <details className="rounded-xl border border-brand-100 bg-white p-5"><summary className="cursor-pointer font-semibold focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand-700"><span aria-hidden="true" className="me-2 inline-block text-brand-700">⌄</span>תחומים ללא דירוג: מיפוי חלקי או חסר</summary><p className="mt-3 text-sm">היעדר ציון אינו חוסר התאמה. מיפויים משוערים אינם מקבלים את ציון המקצוע הרחב.</p><ul className="mt-3 space-y-2 text-sm">{crosswalk.filter(c=>c.mapping!=='direct').map(c=><li key={c.specialty}>{c.specialty} — {c.mapping==='approximate'?'מיפוי משוער בלבד, לא משוקלל':'אין מיפוי אמין'}{!c.catalog?' · מקצוע בסיס נוסף':''}</li>)}</ul><Link className={link} href="/career-fit/sources#coverage">טבלת הכיסוי והמקורות</Link></details>
  <p className="text-sm text-slate-600">מדד התאמה להתמחות אינו מדד המחלקה ואינו התאמה להעדפות מחלקה. שלושתם נשארים נפרדים.</p>
  <EvidenceAttribution/>
 </div>;
}
