import Link from 'next/link';
import {EvidenceAttribution} from '@/components/career-fit/evidence-sources';
import {crosswalk,RIASEC,VERSION} from '@/lib/career-fit/evidence/model';
export const metadata={title:'מקורות ושיטת השאלון | Hitmachut'};
export default function Sources(){return <main dir="rtl" className="mx-auto max-w-5xl space-y-6 px-4 py-8 leading-8"><Link className="text-brand-700 underline" href="/career-fit">חזרה לבחירת התמחות</Link><h1 className="text-3xl font-black">מקורות, שיטה ומגבלות</h1>
<section className="space-y-3"><h2 className="text-2xl font-bold">על השאלון</h2><p>השאלון כולל 30 שאלות רפואיות מקוריות של Hitmachut: חמש שאלות לכל אחד מששת תחומי העניין RIASEC. הניסוחים נוצרו והותאמו לעברית בסיוע כלי בינה מלאכותית; לא הושלמה בדיקה אנושית מקצועית או בדיקת תוקף בעברית. אלה אינם פריטי שאלון O*NET הרשמי.</p><p>המסגרת עוסקת בעניין מעשי, חקר, יצירתיות, עזרה והדרכה, הובלה ועבודה שיטתית. שיוך יצירתיות רפואית ל־Artistic והובלה קלינית ל־Enterprising הוא השערת עבודה, ולא ממצא מתוקף. <a className="underline" href="https://www.onetonline.org/find/descriptor/browse/1.B.1">מסגרת תחומי העניין RIASEC</a>.</p></section>
<section className="space-y-3"><h2 className="text-2xl font-bold">איך מחושב המדד?</h2><p>כל תשובה מקבלת 0–4. ״לא בטוח/ה״ היא תשובה שערכה 2; דילוג נשאר חסר. אין שאלות הפוכות. בכל ממד מסכמים את חמש התשובות ומחלקים ב־20. כל 30 התשובות נדרשות לחישוב; אין השלמת חסרים או שינוי המכנה.</p><p>משווים את ששת הממדים לפרופיל המקצוע במאגר O*NET31.0, שבו ששת הערכים הם בסולם 1–7. מתאם פירסון (Pearson correlation) משווה את צורת הפרופיל לאחר חיסור הממוצע מכל וקטור, ללא תלות ביחידות הסולם. הוא מתעלם מגובה העניין הכללי ורגיש להבדלים קטנים בפרופיל כמעט שטוח. <a className="underline" href="https://www.onetcenter.org/dl_files/Mini-IP_Linking.pdf">רקע מחקרי לשימוש בהשוואת פרופילים</a>; אין בכך תיקוף לפריטים הרפואיים המקוריים באתר.</p><p>מדד ההתאמה הוא <bdi>50 × (1 + r)</bdi>, מעוגל למספר שלם בין 0 ל־100. 50 מציין היעדר קשר ליניארי, ו־100 מציין דפוס זהה; אלה אינם אחוזי הצלחה או הסתברות לקבלה. פרופיל שטוח אינו מקבל דירוג. המיון לפי המתאם לפני העיגול, עם שוויון מספרי עד 12 ספרות וסדר קוד מקצוע לשבירת שוויון בלבד.</p><p>שלושת הכיוונים הבולטים הם בעלי המדדים הגבוהים מבין המתאמים שאינם שליליים. הרשימה המלאה כוללת את כל המיפויים הישירים. בהסבר לכל תחום מוצגים ממדים משותפים והבדלים; דגש נמוך משותף אינו מוצג כעניין גבוה. בפירוט הטכני מוצגות תרומות שסכומן שווה למתאם. אין מהן מסקנה על קצב העבודה, עצמאות, קשר ממושך עם מטופלים או יכולת קלינית.</p></section>
<section className="space-y-3"><h2 id="coverage" className="scroll-mt-36 text-2xl font-bold">כיסוי ההתמחויות</h2><p>28 קטגוריות בקטלוג: 17 מיפויים ישירים, 4 משוערים שאינם מדורגים, 7 ללא מיפוי אמין. מפורטים גם ארבעה מקצועות בסיס נוספים מהמאגר הקודם. ״ישיר״ מתאר התאמה בין שמות ותיאורי מקצוע, ולא הוכחה לשוויון בין מסלולי הכשרה.</p><p>O*NET31.0; נתוני תחומי עניין מתאריך 02/2026, בשיטת Machine Learning/Expert. המקור מתאר מקצועות בארה״ב, לא סקר של מתמחים בישראל. המיפויים המשוערים מוצגים לתיעוד בלבד.</p><div className="overflow-x-auto"><table className="w-full text-right text-sm"><caption className="text-right">הערכים במקור לפי הסדר R,I,A,S,E,C</caption><thead><tr><th className="p-2">תחום</th><th className="p-2">מיפוי</th><th className="p-2">מקצוע במקור</th><th className="p-2">ששת הערכים</th></tr></thead><tbody>{crosswalk.map(c=><tr key={c.specialty} className="border-t"><th className="p-2 font-normal">{c.specialty}{!c.catalog?' (נוסף)':''}</th><td className="p-2">{c.mapping==='direct'?'ישיר':c.mapping==='approximate'?'משוער — ללא ציון':'אין'}</td><td className="p-2">{c.code?<a dir="ltr" className="underline" href={`https://www.onetonline.org/link/summary/${c.code}`}>{c.title} ({c.code})</a>:'—'}{c.code&&<p className="text-xs text-slate-600" dir="ltr">{c.limitation}</p>}</td><td className="p-2"><bdi>{c.scores?RIASEC.map(d=>c.scores![d]).join(', '):'—'}</bdi></td></tr>)}</tbody></table></div></section>
<EvidenceAttribution full/>
<section className="space-y-3"><h2 className="text-2xl font-bold">מגבלות</h2><p>זהו כלי עזר לבחינת העדפות, לא כלי פסיכומטרי מאומת או ייעוץ אישי. לא נבדקו שקילות לממדים המקוריים, מהימנות, יציבות לאורך זמן או יכולת לחזות בחירת התמחות ושביעות רצון. נתוני המקצוע מארה״ב אינם מתארים בהכרח מסלול התמחות בישראל. התנסות קלינית, שיחות עם אנשי התחום ושיקול דעת מקצועי נשארים חיוניים.</p><p>בדיקת רגישות על 500 פרופילים סינתטיים הראתה שינוי בתחום המוביל ב־24.2% מהמקרים תחת רעש תשובות שהוגדר לבדיקה. זו אינה מדידה של משתמשים ואינה הערכה של דיוק. גרסת הפריטים והחישוב: <bdi>{VERSION}</bdi>.</p></section>
<section className="space-y-3"><h2 className="text-2xl font-bold">שמירה ופרטיות</h2><p>כל תשובה נשמרת אוטומטית בדפדפן במכשיר זה, ללא שליחת תשובות לשרת. רענון משחזר את ההתקדמות. ניתן לדלג, לשנות תשובה, לעבור בין שאלות ולמחוק את הטיוטה. טיוטה בת יותר מ־30 יום מהשינוי האחרון נמחקת בכניסה הבאה; אין מחיקה ברקע כשהדפדפן סגור. טיוטות מארכיטקטורה שאינה נתמכת לא נטענות. אם השמירה המקומית חסומה מוצגת הודעה.</p><p>מדד ההתאמה להתמחות אינו מדד המחלקה ואינו התאמה להעדפות מחלקה. <Link className="underline" href="/career-fit/methodology#department-index">שיטת ציוני המחלקה</Link>.</p></section>
</main>;}
